# Generated by Django 5.0.7 on 2024-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_orderdetail_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('value', models.FloatField(verbose_name='Valor Dolar')),
            ],
        ),
    ]
